=== karelzimmer/scripts/python/python-crash-course/PythonData/Xml/Bookstore.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ecr:Bookstore" xmlns:tg="urn:ecr:Bookstore" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- 
	targetNamespace="urn:ecr:Bookstore"

	LET OP: een xsd mag meerdere hfdelem bevatten, maar slechts 1 daarvan mag hfdelem in een xml zijn;
	in bookstore.xml gebr ik elem bookstore als hfdelem, in Dvds.xml elem dvds, maar mag ook dvd als hfdelem
	een ref-attrib MOET altijd verwijzen naar een globaal elem (= hfdelem)
	
	complexType kan bevatten:
		simpleContent (restriction/extension), bv attrib bij elem met xsd:string of xsd:double
		complexContent (restriction/extension), bv sequence toevoegen aan elem met sequence (inheritance)
		annotation, group, sequence, all, choice
	
	Als je in deze xsd eigen globale types of elems definieert, dan bij type/elem-naam NIET prefix 'tg:' gebruiken
	Als je elders in deze xsd hiernaar verwijst, dan moet je prefix 'tg:' juist WEL gebruiken (kreun)
	-->
	<xs:element name="bookstore">
		<xs:complexType mixed="true">			<!-- mixed="true" -->
			<xs:choice maxOccurs="unbounded">
				<xs:element name="book">
					<!-- hier niet type="..", want binnen tag staat complexType of simpleType -->
					<xs:complexType>
						<xs:sequence>
							<!-- vlg prb in NET20: dubbele def van attrib en elem met zelfde naam
							<xs:element name="genre" minOccurs="0" type="xs:string" />-->
							<xs:element name="title" type="tg:titleType" />
							<xs:element name="price" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:double">
											<xs:attribute name="currency" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="stock" type="xs:int" minOccurs="0" default="1" />
							<!-- als je elem leeglaat, dan default; bij weglaten niet -->
							<xs:element name="version" type="xs:float" fixed="1.0" />
							<xs:element name="author" type="tg:authorType" minOccurs="0" maxOccurs="3" />
						</xs:sequence>
						<xs:attribute name="genre" use="required">
							<!-- use = optional | required | prohibited, default: optional -->
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="computer" />
									<xs:enumeration value="cultuur" />
									<xs:enumeration value="filosofie" />
									<xs:enumeration value="literatuur" />
									<xs:enumeration value="sport" />
									<xs:enumeration value="waardeloos" />
									<xs:enumeration value="wetenschap" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="pubdate" type="xs:gYear" />
						<xs:attribute name="isbn" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="record">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string" minOccurs="0" />
							<xs:element name="artist" type="tg:authorType" maxOccurs="5" />
							<xs:element name="song" type="tg:songType" maxOccurs="40" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
					</xs:complexType>
				</xs:element>
				<xs:element ref="tg:dvd" />
				<!-- ref MOET verw naar globaal elem -->
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<!-- einde elem bookstore -->

	<!-- hieronder 2e en 3e hfdelem -->
	<xs:element name="dvds">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="tg:dvd" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dvd">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string" />
				<xs:element name="director" type="tg:authorType" />
				<xs:element name="length" type="xs:float" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- hieronder mijn complexTypes en SimpleType; bij verwijzing prefix tg: gebr -->
	<xs:complexType name="titleType">
		<xs:simpleContent>
			<!-- extension, restriction (van een vorige extension) -->
			<xs:extension base="xs:string">
				<xs:attribute name="remark" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="authorType">
		<xs:all>
			<xs:element name="firstname" type="tg:nameString" minOccurs="0" />
			<xs:element name="lastname" type="tg:nameString" minOccurs="0" />
		</xs:all>
		<!-- xs:all of xs:sequence opgeven in propvenster Visual Studio, prop Order =>wijzigt GroupChild
		xs:all =>alle elems moeten voorkomen, maar mogen in willek volgorde
		-->
	</xs:complexType>

	<xs:simpleType name="nameString">
		<xs:restriction base="xs:string">
			<!-- list, union, restriction -->
			<xs:maxLength value="30" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="songType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="length" type="xs:float" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== karelzimmer/scripts/PythonData/Xml/Bookstore.xml
<?xml version="1.0" encoding="iso-8859-1" ?>

<!--<?xml-stylesheet type='text/xsl' href='Bookstore_boeken_films01_exslt_nodeset.xsl'?>-->

<!--<!DOCTYPE bookstore SYSTEM "Bookstore.dtd">-->

<!--
	Boeken, platen en dvd's kunnen door elkaar staan.

	Je kunt xsd (xml schema) op twee manieren koppelen aan xml:
	a) door bij validatingreader (parser engine) xml EN xsd op te geven
	   xv.Schemas.Add(null, ccBookstoreXsd);	//ipv null mag ook ns,
	   //deze MOET dan overeenkomen met targetNamespace in xsd
	b) door in xml verwijzing naar xsd of xsd's op te geven
	   formaat: ns1 [spatie] xsd1 [spatie] ns2 [spatie] xsd2 [spatie] enz
	   xsd-zoekpad mag GEEN spaties bevatten, dus:
	   fout: xsi:schemaLocation="urn:ecr:Bookstore D:/Mijn Dir/Bookstore.xsd"
	   goed: xsi:schemaLocation="urn:ecr:Bookstore D:/MijnDi~1/Bookstore.xsd"
	   goed: xsi:schemaLocation="urn:ecr:Bookstore Bookstore.xsd"
	
	Xsd-verwijzing toevoegen zonder ns:
	xsi:noNamespaceSchemaLocation="tblCat.xsd"
	Dan moet je in xsd attrib targetNamespace weglaten, of leeglaten met "".

<bookstore xmlns="urn:ecr:Bookstore"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:ecr:Bookstore Bookstore.xsd"
>
-->

<bookstore

>
	<book genre="filosofie" isbn="0-09-111721-6" pubdate="1959" >
		<title remark="orgtitle:Logik der Forschung">The Logic of Scientific Discovery</title>
		<stock>2</stock>
		<version>2.0</version>		<!-- 2.0 <== bewuste validatiefout -->
		<author>
			<lastname>Popper</lastname>
			<firstname>Karl</firstname>
		</author>
	</book>

	<dvd id="1">
		<title>Straw Dogs</title>
		<director><firstname>Sam</firstname><lastname>Peckinpah</lastname></director>
		<length>111</length>
	</dvd>

	<book genre="computer" isbn="1-861005-58-X" >
		<title>ADO.NET Programmer's Reference</title>
		<price>nvt</price>		<!-- nvt <== bewuste validatiefout -->
		<version />
		<!--dotnet geeft bij vlg een validation error, vor ging wel goed -->
		<!--<version></version>-->
	</book>
	<book isbn="1-861005-59-8" genre="computer">
		<title>Beginning XML 2nd Edition</title>
		<price>55.6</price>
		<stock>3</stock>
		<version>1</version>
		<author>
			<firstname>David</firstname>
			<lastname>Hunter</lastname>
		</author>
		<author>
			<firstname>Kurt</firstname>
			<lastname>Cagle</lastname>
		</author>
		<author>
			<firstname>Chris</firstname>
			<lastname>Dix</lastname>
		</author>
	</book>
	<book genre="cultuur" pubdate="2002" isbn="90-5911-024-2">
		<title>Athos</title>
		<price>45.75</price>
		<stock>1</stock>		<!-- als leeg, dan in xsd: default 1 -->
		<version>1.0</version>
		<author>
			<!-- elems in willek volgorde, vanwege xs:all ipv xs:sequence -->
			<lastname>ter Veen</lastname>
			<firstname>Koert</firstname>
		</author>
	</book>
	<book genre="computer" pubdate="2002">
		<title>ASP.NET in a Nutshell</title>
		<version>1</version>
		<author>
			<firstname>Andrew</firstname>
			<lastname>Duthie</lastname>
		</author>
		<author>
			<firstname>Matthew MacDonald</firstname>
		</author>
	</book>
	<book genre="cultuur" pubdate="1998" isbn="0-300-06463-2">
		<title>Learning Irish</title>
		<price currency="punt">26.5</price>	<!-- punt is naam van Ierse pond -->
		<stock>2</stock>
		<version>1</version>
		<author>
			<firstname>Mícheál</firstname>
			<lastname>Ó Siadhail</lastname>
		</author>
	</book>
	
	<record>
		<title>Songs of Love and Hate</title>
		<artist>
			<firstname>Leonard</firstname>
			<lastname>Cohen</lastname>
		</artist>
		<song><title>Avalanche</title><length>4.59</length></song>
		<song><title>Last Year's Man</title><length>5.58</length></song>
		<song><title>Dress Rehearsal Rag</title><length>6.02</length></song>
		<song><title>Diamonds in the Mine</title><length>4.00</length></song>
		<song><title>Love Calls You by Your Name</title><length>5.37</length></song>
		<song><title>Famous Blue Raincoat</title><length>5.06</length></song>
		<song><title>Sing Another Song, Boys</title><length>6.09</length></song>
		<song><title>Joan of Arc</title><length>6.22</length></song>
	</record>

	<record id="102">
		<title>Nashville Skyline</title>
		<artist>
			<firstname>Bob</firstname>
			<lastname>Dylan</lastname>
		</artist>
		<artist>
			<firstname>Johnny</firstname>
			<lastname>Cash</lastname>
		</artist>
		<song><title>Girl From The North Country</title><length>3.38</length></song>
		<song><title>Nashville Skyline Rag</title><length>3.10</length></song>
		<song><title>To Be Alone With You</title><length>2.06</length></song>
		<song><title>I Threw It All Away</title><length>2.21</length></song>
		<song><title>Peggy Day</title><length>1.59</length></song>
		<song><title>Lay Lady Lay</title><length>3.17</length></song>
		<song><title>One More Night</title><length>2.20</length></song>
		<song><title>Tell Me That It Isn't True</title><length>2.38</length></song>
		<song><title>Country Pie</title><length>1.34</length></song>
		<song><title>Tonight I'll Be Staying Here With You</title><length>3.20</length></song>
	</record>

	<dvd id="2">
		<title>Una Giornata Particolare</title>
		<director><firstname>Ettore</firstname><lastname>Scola</lastname></director>
		<length>101</length>
	</dvd>
	<dvd id="3">
		<title>Shoah</title>
		<director><lastname>Lanzmann</lastname><firstname>Claude</firstname></director>
		<length>550</length>	<!-- dwz 9 uur en 10 min -->
	</dvd>
	We moeten eens praten.
</bookstore>
